# Generated by Django 4.2.7 on 2023-11-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0014_alter_leaderboardcompetitiveeasymode_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='LeaderboardCompetitiveEasyMode',
        ),
        migrations.DeleteModel(
            name='LeaderboardCompetitiveExpertMode',
        ),
        migrations.DeleteModel(
            name='LeaderboardCompetitiveHardMode',
        ),
        migrations.DeleteModel(
            name='LeaderboardCompetitiveMediumMode',
        ),
        migrations.DeleteModel(
            name='LeaderboardCompetitiveOhnepixelMode',
        ),
        migrations.DeleteModel(
            name='LeaderboardSurvivalEasyMode',
        ),
        migrations.DeleteModel(
            name='LeaderboardSurvivalExpertMode',
        ),
        migrations.DeleteModel(
            name='LeaderboardSurvivalHardMode',
        ),
        migrations.DeleteModel(
            name='LeaderboardSurvivalMediumMode',
        ),
        migrations.DeleteModel(
            name='LeaderboardSurvivalOhnepixelMode',
        ),
    ]
